/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package betess.presentation;

import betess.business.Aposta;
import betess.business.BetESS;
import betess.business.Evento;
import java.awt.Color;
import javax.swing.JCheckBox;
import javax.swing.JLabel;

/**
 *
 * @author tiagoalves
 */
public class EventoDialog extends javax.swing.JDialog {
    
    private BetESS betEss;
    private Evento evento;
    private Aposta aposta;
    
    /**
     * Creates new form EventoDialog
     * @param parent
     * @param modal
     * @param b
     * @param idEvento
     */
    public EventoDialog(java.awt.Frame parent, boolean modal, BetESS b, int idEvento, Aposta a) {
        super(parent, modal);
        this.betEss = b;
        this.aposta = a;
        this.evento = this.betEss.getEvento(idEvento);
        setUp();
        initComponents();
    }
    
    private void setUp(){
        this.jLabelEquipaUm = new JLabel(this.evento.getEquipaUm());
        this.jLabelEquipaDois = new JLabel(this.evento.getEquipaDois());
        this.oddUm = new JCheckBox();
        this.oddDois = new JCheckBox();
        this.oddX = new JCheckBox();
        this.oddUm.setText(String.valueOf(this.evento.getOddUm()));
        this.oddX.setText(String.valueOf(this.evento.getOddX()));
        this.oddDois.setText(String.valueOf(this.evento.getOddDois()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEvento = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelEquipaUm = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelEquipaDois = new javax.swing.JLabel();
        oddUm = new javax.swing.JCheckBox();
        oddX = new javax.swing.JCheckBox();
        oddDois = new javax.swing.JCheckBox();
        jPanelAddEvento = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanelRemEvento = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelEvento.setBackground(new java.awt.Color(36, 47, 65));
        jPanelEvento.setMaximumSize(new java.awt.Dimension(30000, 30000));

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));

        jLabelEquipaUm.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabelEquipaUm.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEquipaUm.setText(this.evento.getEquipaUm());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");

        jLabelEquipaDois.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabelEquipaDois.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEquipaDois.setText(this.evento.getEquipaDois());

        oddUm.setForeground(new java.awt.Color(255, 255, 255));
        oddUm.setText(String.valueOf(this.evento.getOddUm())
        );

        oddX.setForeground(new java.awt.Color(255, 255, 255));
        oddX.setText(String.valueOf(this.evento.getOddX()));

        oddDois.setForeground(new java.awt.Color(255, 255, 255));
        oddDois.setText(String.valueOf(this.evento.getOddDois())
        );

        jPanelAddEvento.setBackground(new java.awt.Color(255, 102, 102));
        jPanelAddEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAddEventoMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Adicionar Evento");

        javax.swing.GroupLayout jPanelAddEventoLayout = new javax.swing.GroupLayout(jPanelAddEvento);
        jPanelAddEvento.setLayout(jPanelAddEventoLayout);
        jPanelAddEventoLayout.setHorizontalGroup(
            jPanelAddEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddEventoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAddEventoLayout.setVerticalGroup(
            jPanelAddEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddEventoLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(17, 17, 17))
        );

        jPanelRemEvento.setBackground(new java.awt.Color(255, 102, 102));
        jPanelRemEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRemEventoMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Remover Evento");

        javax.swing.GroupLayout jPanelRemEventoLayout = new javax.swing.GroupLayout(jPanelRemEvento);
        jPanelRemEvento.setLayout(jPanelRemEventoLayout);
        jPanelRemEventoLayout.setHorizontalGroup(
            jPanelRemEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRemEventoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRemEventoLayout.setVerticalGroup(
            jPanelRemEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRemEventoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel15)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEquipaUm)
                            .addComponent(oddUm))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jLabel2)
                                .addGap(68, 68, 68)
                                .addComponent(jLabelEquipaDois))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(oddX)
                                .addGap(18, 18, 18)
                                .addComponent(oddDois))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanelAddEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jPanelRemEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEquipaUm)
                    .addComponent(jLabel2)
                    .addComponent(jLabelEquipaDois))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oddUm)
                    .addComponent(oddX)
                    .addComponent(oddDois))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAddEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelRemEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jPanelEventoLayout = new javax.swing.GroupLayout(jPanelEvento);
        jPanelEvento.setLayout(jPanelEventoLayout);
        jPanelEventoLayout.setHorizontalGroup(
            jPanelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEventoLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelEventoLayout.setVerticalGroup(
            jPanelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEventoLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelAddEventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAddEventoMouseClicked
        // TODO add your handling code here:
        if(this.oddUm.isSelected() && !this.oddDois.isSelected() && !this.oddX.isSelected()){
            double odd = Double.valueOf(this.oddUm.getText());
            this.aposta.addEventoToAposta(evento, odd);
            this.dispose();
        }

        else if(!this.oddUm.isSelected() && this.oddDois.isSelected() && !this.oddX.isSelected()){
            double odd = Double.valueOf(this.oddDois.getText());
            this.aposta.addEventoToAposta(evento, odd);
            this.dispose();
        }

        else if(!this.oddUm.isSelected() && !this.oddDois.isSelected() && this.oddX.isSelected()){
            double odd = Double.valueOf(this.oddX.getText());
            this.aposta.addEventoToAposta(evento, odd);
            this.dispose();
        }
    }//GEN-LAST:event_jPanelAddEventoMouseClicked

    private void jPanelRemEventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRemEventoMouseClicked
        // TODO add your handling code here:
        this.aposta.remEventoFromAposta(evento);
        this.dispose();
    }//GEN-LAST:event_jPanelRemEventoMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelEquipaDois;
    private javax.swing.JLabel jLabelEquipaUm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAddEvento;
    private javax.swing.JPanel jPanelEvento;
    private javax.swing.JPanel jPanelRemEvento;
    private javax.swing.JCheckBox oddDois;
    private javax.swing.JCheckBox oddUm;
    private javax.swing.JCheckBox oddX;
    // End of variables declaration//GEN-END:variables
}
